name: Release NR Tracing Layer

on:
  push:
    tags:
      - 'v*.*.*-nr-tracing-layer'
  workflow_dispatch:

jobs:
  crates:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: stable
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to crates.io
        run: |
          cargo login ${{secrets.crates_key}}
          cargo publish -p nr-tracing-layer
